### ISSUE TITLE
Example demonstrating sharing of one secret to multiple recipients

### ISSUE THREAD

**Issue by numbat** [Covata/delta-sdk-java#2]
The example should demonstrate the following:

- one identity sharing a base secret with multiple other identities
- other identities acting on their respective derived secret
- retrieval of an event log for the secret showing these actions

**Comment by numbat** [comment]
I imagine the output to the command line would be something like this:

- identity A created
- identity B created
- identity C created
- identity A creates base secret S
- identity A shares S with B (creating derived secret Sb)
- identity A shares S with C (creating derived secret Sc)
- identity B accesses derived secret Sb (should be success)
- identity B accesses derived secret Sc (should be error)
- identity C accesses derived secret Sc (should be success)
- identity A lists events related the access of the secret and see the above actions

**Comment by rbartlet** [comment]
There is something else that I have in mind regarding input. Perhaps read input from a file, and treat each line of input as something to be protected by a separate secret, to show a form of stream-based processing.

**Comment by numbat** [comment]
Can do - basically have a loop through a "stream" of data in the file replicating the steps:

- identity A creates base secret Sn
- identity A shares Sn
- recipient identity (or identities) access Sn
- identity A lists events related the access Sn

Where each line in the file represents a "message" with intended recipients.
